baseURL = "https://polacik.org/"
languageCode = "en-uk"
defaultContentLanguage = "en"
title = "Peter Polacik - Freelancer and Woodworker"
theme = "hugo-material-blog"
publishDir = "docs"

paginate = 3
paginatePath = "page"

copyright = "Copyright (c) 2020 Peter Polacik"

[permalinks]
    post = "/:year/:month/:title/"

# English
[languages.en]
    languageName = "English"

    # Main menu
    [[languages.en.menu.main]]
        url = "/"
        name = "Home"
        weight = 1

    # Footer menu 1
    [[languages.en.menu.footer1]]
        url = "#"
        name = "Service N"
        weight = 1

    # Footer menu 2
    [[languages.en.menu.footer2]]
        url = "/"
        name = "Home"
        weight = 1
    [[languages.en.menu.footer2]]
        url = "/about/"
        name = "About"
        weight = 2

    # Include menus in footer
    [[languages.en.params.footer_menus]]
        name = "Services"
        menu = "footer2"
    [[languages.en.params.footer_menus]]
        name = "Links"
        menu = "footer1"

# Slovak
[languages.sk]
    languageName = "Slovenčina"

    # Main menu
    [[languages.sk.menu.main]]
        url = "/sk/"
        name = "Domov"
        weight = 1

    # Footer menu 1
    [[languages.sk.menu.footer1]]
        url = "#"
        name = "Služba N"
        weight = 1

    # Footer menu 2
    [[languages.sk.menu.footer2]]
        url = "/sk/"
        name = "Domov"
        weight = 1
    [[languages.sk.menu.footer2]]
        url = "/about/"
        name = "O mne"
        weight = 2

    # Include menus in footer
    [[languages.sk.params.footer_menus]]
        name = "Služby"
        menu = "footer2"
    [[languages.sk.params.footer_menus]]
        name = "Odkazy"
        menu = "footer1"

[params]
    # Display post summaries instead of content in list templates (default: true)
    # truncate = false
