baseURL = "https://polacik.org"
languageCode = "en-uk"
title = "Peter Polacik - Freelancer and Woodworker"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Peter Polacik"
    description = "Freelancer and Woodworker"
    email = "peter@polacik.org"
    phone = "+421 951 167 893"
    address = "I. Olbrachta 988/19, 028 01 Trstena, Slovakia"
    year = 2020
    avatar = "images/peter.jpg"
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/polacikp"
    icon = "fab fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/pepol42"
    icon = "fab fa-instagram"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/peterpolacik"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/pepol"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:peter@polacik.org"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
