baseURL = "https://polacik.org"
languageCode = "en-uk"
title = "Peter Polacik"
copyright = "Copyright 2020 Peter Polacik <peter@polacik.org>"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
enableRobotsTXT = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    favicon = ""
    description = "Freelancer and Woodworker"
    facebook = "https://facebook.com/polacikp"
    instagram = "https://instagram.com/pepol42"
    github = "https://github.com/pepol"
    linkedin = "https://www.linkedin.com/in/peterpolacik"
    background_color_class = "bg-black"
    featured_image = "/images/header.jpg"
    recent_posts_number = 2
